export default {
  ADD_SMURF_START     : 'ADD_SMURF_START',
  ADD_SMURF_SUCCESS   : 'ADD_SMURF_SUCCESS',
  ADD_SMURF_FAIL      : 'ADD_SMURF_FAIL',
  UPDATE_SMURF_START  : 'UPDATE_SMURF_START',
  UPDATE_SMURF_SUCCESS: 'UPDATE_SMURF_SUCCESS',
  UPDATE_SMURF_FAILURE: 'UPDATE_SMURF_FAILURE',
  DELETE_SMURF_START  : 'DELETE_SMURF_START',
  DELETE_SMURF_SUCCESS: 'DELETE_SMURF_SUCCESS',
  DELETE_SMURF_FAILURE: 'DELETE_SMURF_FAILURE',
  FETCH_SMURF_START   : 'FETCH_SMURF_START',
  FETCH_SMURF_SUCCESS : 'FETCH_SMURF_SUCCESS',
  FETCH_SMURF_FAILURE : 'FETCH_SMURF_FAILURE',
}